# Site settings
title: AndresTech | Un blog sobre la tecnologia
description: "Pequeño blog sobre tecnologia actual"
url: "http://www.dyutibarma.github.io/monochrome"
author:
  name: "Andres Felip Usma Montenegr"
  email: "andresfelipeusma@gmail.com"
  url: "https://andresfelipeusma.github.io"

# Build settings
#baseurl: /monochrome # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:categories/:title
paginate: 4
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
